### PR TITLE
Remove upper version bound for Interpolations

### PR DESCRIPTION
**Pull request by Element-126**
As suggested by @andreasnoack (cf. discussion in #61).

### CODE REVIEW

**Comment by Element-126** [comment]
Should we tag a bugfix release (v0.5.2) to resolve the dependency resolution ambiguity?

**Comment by andreasnoack** [comment]
Either that or er could just remove the current bound in METADATA.

**Comment by Element-126** [comment]
I would rather trust your judgement here.

**Comment by andreasnoack** [comment]
Okay. I've just opened https://github.com/JuliaLang/METADATA.jl/pull/19262.

**Comment by Element-126** [comment]
Thanks!

**Pull request merged**
