### PR TITLE
Document that slots can be accessed as part of the API.

### LINKED ISSUE #67: accessors for gridpoints and corresponding densities
It is unclear if eg for univariate densities the slots `x` and `density` can be used (ie are part of the API and can be expected to be stable, not an internal implementation detail).

It would be great to document this, or alternatively provide accessor functions. Similarly for bivariate.

If the package maintainers clarify their intention, I would be happy to make a PR.

### PR DESCRIPTION
**Pull request by tpapp**
Fixes #67. Also documents the intepretation of the integral.

(All of these properties are already tested for.)

### CODE REVIEW

**Comment by tpapp** [comment]
@tlnagy, since you were also interested in this issue a review would be appreciated.

**Comment by tlnagy** [comment]
Looks good. I think that makes it a lot clearer.

Would it make more sense to use accessor functions for accessing the gridpoints and density values? It would allow for changes in the underlying type without breaking the API, but that might not be necessary.

**Comment by tpapp** [comment]
Thanks. Accessors are generally fine, but I want to make minimal changes for now (and later on one can always define `getproperty` to customize this further).

Can someone please merge this?

**Comment by tpapp** [comment]
friendly ping, can someone please merge this?

I would like to proceed with https://github.com/KristofferC/PGFPlotsX.jl/issues/143 which hinges on this.

**Pull request merged**
