### PR TITLE
Remove plots from package

### PR DESCRIPTION
**Pull request by ranjanan**
cc: @ararslan @tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
delete the notebooks too I guess if they're way out of date? @simonbyrne

**Comment by ranjanan** [comment]
@ararslan I removed the outdated notebooks. Does this PR look okay?

**Comment by ararslan** [comment]
It looks great to me! Thanks for doing this. @tkelman had pinged @simonbyrne so I had been waiting for Simon to say something since he's the one who initially added the notebooks to the repo.

**Comment by ranjanan** [comment]
Oh right, I missed that. I'll wait for Simon to comment. :)

**Comment by simonbyrne** [comment]
Fine by me: the plots stuff should really be in something like Plots.jl

**Pull request merged**
